---
title: "Introduction to time"
teaching: 42
exercises: 47
questions: 
- "What is time?"
- "Various issues when working with time"
objectives:
- "Understand how time is defined in the context of R"
- "Get a glimpse of how complicated this actually is"
keypoints:
- "People assume that time is a strict progression of cause to effect, but *actually* from a non-linear, non-subjective viewpoint - it's more like a big ball of wibbly wobbly... time-y wimey... stuff."
source: Rmd
---

## It's complicated




"People assume that time is a strict progression of cause to effect, but *actually* from a non-linear, non-subjective viewpoint - it's more like a big ball of wibbly wobbly... time-y wimey... stuff."

<iframe width="560" height="315" src="https://www.youtube.com/embed/q2nNzNo_Xps" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

- Doctor Who, Blink, 

Alternatively we could take a look at this rant from geeky youtuber Tom Scott, who explains the reasons for this being quite difficult:

<iframe width="560" height="315" src="https://www.youtube.com/embed/-5wpm-gesOY" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

> ## TL;DR
>
> What we learn from looking at writing code for handling time and dates is that what you do, is you put away your code, you don't try and write anything to deal with this. You look at the people who have been there before you. You look at the first people, the people who have dealt with this before, the people who have built the spaghetti code, and you go to them, and you thank them very much for making it open source, and you give them credit, and you take what they have made and you put it in your program, and you never ever look at it again, because that way lies madness
{: .callout}

A point of time in R is defined as the number of seconds after, or before a fixed point in time.

> ## Some of the many problems
> Given a point of time. Now! What is the current time in our timezone? And what is the current time in New York?
> We tend to think of timezones as whole number intervals. 
> But Australia is 9½ hours ahead of London.
> Nepal is 5 1/4 hours ahead of London.
> What about daylight savings time (DST)? Great Britain chages an hour before us.
> And some times countries change the date for the introduction of DST with short notice.
> Also remember that DST in Denmark moves the clock ahead in summer. But Australia moves it ahead in autum.
> Some countries misses dates. Samoa jumped from december 29th 2011 to december 31st 2011, when the moved (administratively) from one side of the international dateline to the other.
{: .callout}

The solution to these problems is to use UTC, Universal Coordinated Time in combination with the Posix time, also known as Unix time or Epoch time.

> ## Why UTC?
> Two reasons. The french suggested TUC, the english speaking world CUT. UTC is the compromise that left noone satisfied.
{: .callout}

Posix time define an instant on the timeline as the number of seconds elapsed since 00:00:00 UTC on January 1st 1970. Time before that arbitrarily selected date is counted as negative seconds.

We are not going to go into leap seconds and the specifics of how Posix time is adjusted to keep it in sync with UTC. That way lies madness.

For the purposes of this introduction, we are going to disregard leap seconds, positive as well as negative, and go with the definition that a point in time is given by the number of seconds (or milliseconds or whatever resolution we need), after or before 00:00:00 UTC on January 1st 1970.

As hinted to handling times and dates is not easy, and fortunately someone else has written libraries that make everything not easy, but easier.

We are going to be working with two libraries, lubridate, which is part of the tidyverse, and zoo.

Lubridate handles most of the things we need to do with time. Zoo provides infrastructure for handling time-series, an important, but confusing topic in itself. We are going to be using it for handling irregular time, like quarters and months.

We are working with a limited number of phenomenons regarding time:

- instant - a point in time.
- a duration. A given span of time, like days and weeks. They have a specific length measured in seconds, and even though we can work with a duration of a year or month, we are not going to, since months and years have variable length
- interval
- period



{% include links.md %}